apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-clusterip
  labels:
    app: dp-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dp-clusterip
  template:
    metadata:
      labels:
        app: dp-clusterip
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip
spec:
  type: ClusterIP
  selector:
    app: dp-clusterip
  ports:
  - protocol: TCP
    port: 80            # 서비스 포트
    targetPort: 80      # Pod의 컨테이너 포트
