apiVersion: v1
kind: Pod
metadata:
  labels:
    run: po-nginx
  name: po-nginx
spec:
  containers:
  - image: docker.io/library/nginx
    name: nginx 
    ports:
    - containerPort: 80
      hostPort: 8080